name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    ci:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: C, C++: Set up clang-format
        run: |
          apt-get install clang-format
      - name: C, C++: Run clang-format
        run: |
          clang-format . -iname *.c -o -iname *.cc -o -iname *.h | xargs clang-format -i

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
      - name: Python: Run pyright
        run: |
          pyright .
      - name: Python: Run ruff
        run: |
          ruff .

      - name: Build
        run: |
          ./scripts/build.sh
      - name: Test
        run: |
          ./scripts/test.sh
