name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

    ci:

      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux packages
        run: |
          sudo apt-get install -y \
            clang-format \
            libxinerama-dev \
            libxrandr-dev

      - name: Install Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Build C++
        run: |
          git submodule update --init --recursive
          cmake -S . -B build
          cmake --build build --target install

      - name: Build Python
        run: |
          python -m pip install --upgrade build pip setuptools
          python -m pip install -r $CWD/requirements.txt
          python -m build . && python3 -m pip install .

      - name: Run GoogleTest
        run: |
          cd build && ctest

      - name: Run pytest
        run: |
          ./scripts/test.sh
    
      - name: Lint C++
        run: |
          find . -iname *.c -o -iname *.cc -o -iname *.h | xargs clang-format -i

      - name: Lint Python
        run: |
          ruff tests
