name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

    ci:

      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Build
        run: |
          ./scripts/build.sh

      - name: Run mypy
        run: |
          source ./venv/bin/active && mypy .

      - name: Run ruff
        run: |
          source ./venv/bin/active && ruff .

      - name: Set up clang-format
        run: |
          sudo apt-get install clang-format

      - name: Run clang-format
        run: |
          find . -iname *.c -o -iname *.cc -o -iname *.h | xargs clang-format -i

      - name: Test
        run: |
          ./scripts/test.sh
